name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy clean build to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          # Clone Hugging Face Space
          git clone https://huggingface.co/spaces/sherki-prerna/Samp hf-space
          cd hf-space

          # Authenticate
          git config credential.helper store
          printf "https://sherki-prerna:%s@huggingface.co\n" "$HF_TOKEN" > ~/.git-credentials

          # Remove existing files
          rm -rf *

          # Copy only backend + deployment files
          cp -r ../backend/* .
          cp ../Dockerfile .
          cp ../requirements.txt .

          git add .
          git commit -m "Auto deploy from GitHub Actions" || echo "No changes"
          git push origin main --force
